config/routes.rb
Medicine::Application.routes.draw do
  devise_for :users

  resources :meds do
    collection do
      get 'list'
    end
    
    member do
      get 'order'
    end
  end
  

  root :to => 'meds#index'

end

app/models/med.rb
class Med < ActiveRecord::Base
  attr_accessible :name, :quantity, :order_code
  
  def implement_order
    code_string = self.order_code
    # symbolic_order_code =  order_code.to_sym
    # proc_order_code = symbolic_order_code.to_proc
    # output = proc_order_code.call
    output = eval("begin $stdout = StringIO.new; #{code_string}; $stdout.string;
ensure $stdout = STDOUT end")
    return output
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
  
end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
  # GET /meds
  # GET /meds.json
  def index
    @meds = Med.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meds }
    end
  end

  def list
    @meds = Med.all
    render :list
  end
  
  # GET /meds/1
  # GET /meds/1.json
  def show
    @med = Med.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @med }
    end
  end

  # GET /meds/new
  # GET /meds/new.json
  def new
    @med = Med.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @med }
    end
  end

  # GET /meds/1/edit
  def edit
    @med = Med.find(params[:id])
  end

  # POST /meds
  # POST /meds.json
  def create
    @med = Med.new(params[:med])

    respond_to do |format|
      if @med.save
        format.html { redirect_to @med, notice: 'Med was successfully created.' }
        format.json { render json: @med, status: :created, location: @med }
      else
        format.html { render action: "new" }
        format.json { render json: @med.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meds/1
  # PUT /meds/1.json
  def update
    @med = Med.find(params[:id])

    respond_to do |format|
      if @med.update_attributes(params[:med])
        format.html { redirect_to @med, notice: 'Med was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @med.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meds/1
  # DELETE /meds/1.json
  def destroy
    @med = Med.find(params[:id])
    @med.destroy

    respond_to do |format|
      format.html { redirect_to meds_url }
      format.json { head :no_content }
    end
  end
  
  def order
    @med = Med.find(params[:id])
    @output = @med.implement_order
    
    respond_to do |format|
      format.html { render :action => "order" }
      format.json { render json: output}
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= yield %>
  <% else %>
    <%= yield %>
  <% end %>
</body>
</html>

app/views/meds/_form.html.erb
<%= form_for(@med) do |f| %>
  <% if @med.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@med.errors.count, "error") %> prohibited this med from being saved:</h2>

      <ul>
      <% @med.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :quantity %> 
  <%= f.text_field :quantity %>
  <br/>
  <%= f.label	  :order_code %> 
  <%= f.text_area :order_code %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meds/edit.html.erb
<h1>Editing med</h1>

<%= render 'form' %>

<%= link_to 'Show', @med %> |
<%= link_to 'Back', meds_path %>

app/views/meds/index.html.erb
<h1>ADMIN MEDS PAGE</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Code for placing order</th>
    <th>Ordered Quantity</th>
    <th>Action</th>
  </tr>

<% @meds.each do |med| %>
  <tr>
    <td><%= med.id %></td>
    <td><%= link_to med.name, med %></td>
    <td><%= med.order_code %></td>
    <td><%= med.quantity %></td>
    <td><%= link_to 'Edit', edit_med_path(med) %> | <%= link_to 'Destroy', med, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Med', new_med_path %>

app/views/meds/list.html.erb
<h1>ADMIN MEDS PAGE</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Ordered Quantity</th>
    <th>Action</th>
  </tr>

<% @meds.each do |med| %>
  <tr>
    <td><%= med.id %></td>
    <td><%= link_to med.name, med %></td>
    <td><%= med.quantity %></td>
    <td><%= link_to 'Order', order_med_path(med) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/meds/new.html.erb
<h1>New med</h1>

<%= render 'form' %>

<%= link_to 'Back', meds_path %>

app/views/meds/order.html.erb
<h1><%= @output %></h1>

app/views/meds/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
 <li>ID:		       <%= @med.id %></li>	    
 <li>Name:		       <%= @med.name %></li>
 <li>Code for placing order:   <%= @med.order_code %></li>
 <li>Ordered Quantity:	       <%= @med.quantity %></li> 
</ul>

<%= link_to 'Edit', edit_med_path(@med) %> |
<%= link_to 'Back', meds_path %>